# redis配置
spring:
    redis:
        cluster:
            nodes:
                - 127.0.0.1:6380
                - 127.0.0.1:6381
                - 127.0.0.1:6382
                - 127.0.0.1:6383
                - 127.0.0.1:6384
                - 127.0.0.1:6385
        lettuce:
            pool:
                max-active: 100
                max-idle: 10
                min-idle: 5
                max-wait: 1000
        redisson:
            clusterServersConfig:
                nodeAddresses:   
                    - redis://127.0.0.1:6380
                    - redis://127.0.0.1:6381
                    - redis://127.0.0.1:6382
                    - redis://127.0.0.1:6383
                    - redis://127.0.0.1:6384
                    - redis://127.0.0.1:6385
